volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared

  wal-vol:
    name: ${WAL_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
